#pragma once

// Dumped with Dumper-7!


namespace SDK
{
//---------------------------------------------------------------------------------------------------------------------
// CLASSES
//---------------------------------------------------------------------------------------------------------------------

// 0x30 (0xEE0 - 0xEB0)
// BlueprintGeneratedClass PrimalItem_WeaponTorch.PrimalItem_WeaponTorch_C
class UPrimalItem_WeaponTorch_C : public UPrimalItemWeaponGenericAmmoless_C
{
public:
	struct FPointerToUberGraphFrame              UberGraphFrame;                                    // 0xEB0(0x8)(ContainsInstancedReference, AssetRegistrySearchable, SimpleDisplay, Protected, BlueprintAuthorityOnly, TextExportTransient, NonPIEDuplicateTransient, PersistentInstance, UObjectWrapper, NativeAccessSpecifierPublic, NativeAccessSpecifierProtected, NativeAccessSpecifierPrivate)
	double                                       DurabilityLossPerSecond;                           // 0xEB8(0x8)(None)
	struct FLinearColor                          TorchOnBeltWidgetTextColor;                        // 0xEC0(0x10)(None)
	class FString                                TorchOnBeltWidgetText;                             // 0xED0(0x10)(None)

	static class UClass* StaticClass();
	static class UPrimalItem_WeaponTorch_C* GetDefaultObj();

	void BPPreventNewColorization(bool ReturnValue, bool CallFunc_IsTorchOnBelt_bIsOnBelt);
	void GetFlameColorIndex(int32 Index, class FName CallFunc_MakeLiteralName_ReturnValue, bool CallFunc_IsValid_ReturnValue, bool CallFunc_EqualEqual_NameName_ReturnValue, int32 CallFunc_SelectInt_ReturnValue);
	void UpdateBeltTorchMeshColors(bool CallFunc_IsServer_ReturnValue, class AActor* CallFunc_GetOwner_ReturnValue, bool CallFunc_IsTorchOnBelt_bIsOnBelt, class AShooterCharacter* K2Node_DynamicCast_AsShooter_Character, bool K2Node_DynamicCast_bSuccess, class APrimalBuff* CallFunc_GetBeltTorchBuffInstanceForCharacter_BeltTorchBuff, class ABuff_BeltTorch_C* K2Node_DynamicCast_AsBuff_Belt_Torch, bool K2Node_DynamicCast_bSuccess_1);
	void BPShouldHideTopLevelCustomContextMenuOption(class FName ContextItem, bool ReturnValue, bool CallFunc_EqualEqual_NameName_ReturnValue, bool CallFunc_EqualEqual_NameName_ReturnValue_1, class AShooterCharacter* CallFunc_GetOwnerPlayer_ReturnValue, class APlayerController* CallFunc_GetPlayerController_ReturnValue, bool CallFunc_IsValid_ReturnValue, class APawn* CallFunc_K2_GetPawn_ReturnValue, bool CallFunc_EqualEqual_ObjectObject_ReturnValue);
	void BPPreventWeaponEquip(bool ReturnValue, bool CallFunc_CanTorchBeOnBelt_bCanBeOnBelt, bool CallFunc_IsTorchOnBelt_bIsOnBelt, class AActor* CallFunc_GetOwner_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, class AShooterCharacter* K2Node_DynamicCast_AsShooter_Character, bool K2Node_DynamicCast_bSuccess, class AShooterWeapon* CallFunc_GetWeapon_ReturnValue, bool CallFunc_IsServer_ReturnValue);
	void RemoveTorchFromBelt(class AShooterCharacter* ForCharacter, class APrimalBuff* CallFunc_GetBeltTorchBuffInstanceForCharacter_BeltTorchBuff, class ABuff_BeltTorch_C* K2Node_DynamicCast_AsBuff_Belt_Torch, bool K2Node_DynamicCast_bSuccess);
	void PutTorchOnBelt(class AShooterCharacter* ForCharacter, bool CallFunc_IsServer_ReturnValue, bool CallFunc_CanStartWeaponSwitch_ReturnValue, class UClass* CallFunc_Conv_SoftClassReferenceToClass_ReturnValue, class UClass* K2Node_ClassDynamicCast_AsShooter_Weapon, bool K2Node_ClassDynamicCast_bSuccess, class UObject* CallFunc_GetClassDefaultObject_ReturnValue, class AWeap_Torch_Base_C* K2Node_DynamicCast_AsWeap_Torch_Base, bool K2Node_DynamicCast_bSuccess, class APrimalBuff* CallFunc_GetBuff_ReturnValue, bool CallFunc_IsValid_ReturnValue, class APrimalBuff* CallFunc_StaticAddBuff_ReturnValue, bool CallFunc_IsValidClass_ReturnValue, class ABuff_BeltTorch_C* K2Node_DynamicCast_AsBuff_Belt_Torch, bool K2Node_DynamicCast_bSuccess_1);
	void CanTorchBeOnBelt(bool bCanBeOnBelt, class UClass* CallFunc_Conv_SoftClassReferenceToClass_ReturnValue, class UClass* K2Node_ClassDynamicCast_AsShooter_Weapon, bool K2Node_ClassDynamicCast_bSuccess, class UObject* CallFunc_GetClassDefaultObject_ReturnValue, class AWeap_Torch_Base_C* K2Node_DynamicCast_AsWeap_Torch_Base, bool K2Node_DynamicCast_bSuccess);
	void GetBeltTorchBuffInstanceForCharacter(class AShooterCharacter* ShooterCharacter, class APrimalBuff* BeltTorchBuff, bool CallFunc_IsValid_ReturnValue, class UClass* CallFunc_Conv_SoftClassReferenceToClass_ReturnValue, class UClass* K2Node_ClassDynamicCast_AsShooter_Weapon, bool K2Node_ClassDynamicCast_bSuccess, class UObject* CallFunc_GetClassDefaultObject_ReturnValue, class AWeap_Torch_Base_C* K2Node_DynamicCast_AsWeap_Torch_Base, bool K2Node_DynamicCast_bSuccess, class APrimalBuff* CallFunc_GetBuff_ReturnValue, bool CallFunc_IsValidClass_ReturnValue);
	void IsCustomContextMenuItemEnabled(class FName ContextItem, bool ReturnValue, bool CallFunc_CanTorchBeOnBelt_bCanBeOnBelt, bool CallFunc_EqualEqual_NameName_ReturnValue, bool CallFunc_EqualEqual_NameName_ReturnValue_1, bool CallFunc_IsTorchOnBelt_bIsOnBelt, bool CallFunc_Not_PreBool_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, bool CallFunc_BooleanAND_ReturnValue_1);
	void IsTorchOnBelt(bool bIsOnBelt, int32 CallFunc_BPGetItemID_ItemID1, int32 CallFunc_BPGetItemID_ItemID2, bool CallFunc_IsValid_ReturnValue, class AActor* CallFunc_GetOwner_ReturnValue, class AShooterCharacter* K2Node_DynamicCast_AsShooter_Character, bool K2Node_DynamicCast_bSuccess, class APrimalBuff* CallFunc_GetBeltTorchBuffInstanceForCharacter_BeltTorchBuff, class ABuff_BeltTorch_C* K2Node_DynamicCast_AsBuff_Belt_Torch, bool K2Node_DynamicCast_bSuccess_1, bool CallFunc_EqualEqual_IntInt_ReturnValue, bool CallFunc_EqualEqual_IntInt_ReturnValue_1, bool CallFunc_EqualEqual_IntInt_ReturnValue_2, bool CallFunc_BooleanAND_ReturnValue, bool CallFunc_EqualEqual_IntInt_ReturnValue_3, bool CallFunc_Not_PreBool_ReturnValue, bool CallFunc_BooleanAND_ReturnValue_1, bool CallFunc_BooleanAND_ReturnValue_2);
	void BPGetCustomInventoryWidgetText(const class FString& ReturnValue, bool CallFunc_IsTorchOnBelt_bIsOnBelt, const class FString& CallFunc_SelectString_ReturnValue);
	void BPGetCustomInventoryWidgetTextColor(const struct FColor& ReturnValue, const struct FLinearColor& NewLocalVar, bool Temp_bool_Variable, const struct FColor& Temp_struct_Variable, bool CallFunc_IsTorchOnBelt_bIsOnBelt, const struct FColor& CallFunc_Conv_LinearColorToColor_ReturnValue, const struct FColor& K2Node_Select_Default);
	void ApplyingSkinOntoItem(class UPrimalItem* ToOwnerItem, bool bIsFirstTime, int32 CallFunc_GetFlameColorIndex_Index, const struct FLinearColor& CallFunc_GetItemCustomColor_outColor, bool CallFunc_GetItemCustomColor_ReturnValue, const struct FCustomItemData& CallFunc_GetCustomItemData_OutData, bool CallFunc_GetCustomItemData_ReturnValue, float CallFunc_BreakColor_R, float CallFunc_BreakColor_G, float CallFunc_BreakColor_B, float CallFunc_BreakColor_A, float CallFunc_Array_Get_Item, const TArray<float>& K2Node_MakeArray_Array, class UPrimalItemArmor_SaddleGeneric_C* K2Node_DynamicCast_AsPrimal_Item_Armor_Saddle_Generic, bool K2Node_DynamicCast_bSuccess, bool CallFunc_IsValid_ReturnValue, double CallFunc_GetGameTimeInSeconds_ReturnValue, const TArray<class FName>& K2Node_MakeArray_Array_1, const TArray<class UClass*>& K2Node_MakeArray_Array_2, const TArray<class UObject*>& K2Node_MakeArray_Array_3, const TArray<class FString>& K2Node_MakeArray_Array_4, int32 CallFunc_GetItemStatValues_ReturnValue, const struct FCustomItemData& K2Node_MakeStruct_CustomItemData, double CallFunc_Conv_IntToDouble_ReturnValue, int32 CallFunc_GetItemStatValues_ReturnValue_1, double CallFunc_Conv_IntToDouble_ReturnValue_1, double CallFunc_Conv_ByteToDouble_ReturnValue, float CallFunc_GetItemStatModifier_ReturnValue, const TArray<float>& K2Node_MakeArray_Array_5, const struct FCustomItemData& K2Node_MakeStruct_CustomItemData_1, float K2Node_MakeArray__3__ImplicitCast, float K2Node_MakeArray__2__ImplicitCast, float K2Node_MakeArray__1__ImplicitCast);
	void RemovedSkinFromItem(class UPrimalItem* FromOwnerItem, bool bIsFirstTime, class UPrimalItemArmor_SaddleGeneric_C* K2Node_DynamicCast_AsPrimal_Item_Armor_Saddle_Generic, bool K2Node_DynamicCast_bSuccess, const struct FCustomItemData& CallFunc_GetCustomItemData_OutData, bool CallFunc_GetCustomItemData_ReturnValue, float CallFunc_Array_Get_Item, float CallFunc_Array_Get_Item_1, int32 CallFunc_FFloor_ReturnValue, int32 CallFunc_FFloor_ReturnValue_1, float CallFunc_Array_Get_Item_2, int32 CallFunc_FFloor_ReturnValue_2, uint8 CallFunc_Conv_IntToByte_ReturnValue, double CallFunc_FFloor_A_ImplicitCast, double CallFunc_FFloor_A_ImplicitCast_1, double CallFunc_FFloor_A_ImplicitCast_2);
	void SkinEquippedBlueprintTick(class UPrimalItem* OwnerItem, float DeltaSeconds, class UPrimalItemArmor_SaddleGeneric_C* K2Node_DynamicCast_AsPrimal_Item_Armor_Saddle_Generic, bool K2Node_DynamicCast_bSuccess, int32 Temp_int_Variable, const struct FCustomItemData& CallFunc_GetCustomItemData_OutData, bool CallFunc_GetCustomItemData_ReturnValue, class UActorComponent* CallFunc_GetAttachedComponent_ReturnValue, class UNiagaraComponent* K2Node_DynamicCast_AsNiagara_Particle_System_Component, bool K2Node_DynamicCast_bSuccess_1, class UParticleSystemComponent* K2Node_DynamicCast_AsCascade_Particle_System_Component, bool K2Node_DynamicCast_bSuccess_2, class UPointLightComponent* K2Node_DynamicCast_AsPoint_Light_Component, bool K2Node_DynamicCast_bSuccess_3, bool K2Node_SwitchName_CmpSuccess, float CallFunc_Array_Get_Item, float CallFunc_Array_Get_Item_1, float CallFunc_Array_Get_Item_2, float CallFunc_Array_Get_Item_3, const struct FLinearColor& K2Node_MakeStruct_LinearColor, int32 CallFunc_Add_IntInt_ReturnValue, const struct FVector& CallFunc_Conv_LinearColorToVector_ReturnValue, int32 CallFunc_GetAttachedComponentsNum_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue, bool CallFunc_LessEqual_IntInt_ReturnValue, bool CallFunc_LessEqual_DoubleDouble_ReturnValue, bool CallFunc_IsValid_ReturnValue, enum class ENetworkModeResult CallFunc_CanRunCosmeticEvents_OutNetworkMode, bool K2Node_SwitchEnum_CmpSuccess, bool CallFunc_IsServer_ReturnValue, double CallFunc_GetGameTimeInSeconds_ReturnValue, double CallFunc_Subtract_DoubleDouble_ReturnValue, bool CallFunc_Greater_DoubleDouble_ReturnValue, double CallFunc_Multiply_DoubleDouble_ReturnValue, double CallFunc_Subtract_DoubleDouble_ReturnValue_1, double CallFunc_FMax_ReturnValue, double CallFunc_LessEqual_DoubleDouble_A_ImplicitCast, double CallFunc_Subtract_DoubleDouble_A_ImplicitCast, float K2Node_VariableSet_ItemDurability_ImplicitCast);
	void BPPreventUseOntoItem(class UPrimalItem* DestinationItem, bool ReturnValue, bool bRetValue, int32 CallFunc_And_IntInt_ReturnValue, bool CallFunc_NotEqual_ObjectObject_ReturnValue, bool CallFunc_NotEqual_IntInt_ReturnValue, bool CallFunc_LessEqual_DoubleDouble_ReturnValue, double CallFunc_LessEqual_DoubleDouble_A_ImplicitCast);
	void BPPreUseItem();
	void BPNotifyItemRefreshed();
	void SelectedCustomContextMenuItem(class FName ContextItem, class AShooterPlayerController* ForPC);
	void BPUsedOntoItem(class UPrimalItem* DestinationItem, int32 AdditionalData);
	void ExecuteUbergraph_PrimalItem_WeaponTorch(int32 EntryPoint, bool CallFunc_IsServer_ReturnValue, bool CallFunc_IsServer_ReturnValue_1, bool CallFunc_IsTorchOnBelt_bIsOnBelt, class AActor* CallFunc_GetOwner_ReturnValue, class UClass* CallFunc_Conv_SoftClassReferenceToClass_ReturnValue, class AShooterCharacter* K2Node_DynamicCast_AsShooter_Character, bool K2Node_DynamicCast_bSuccess, class UClass* K2Node_ClassDynamicCast_AsShooter_Weapon, bool K2Node_ClassDynamicCast_bSuccess, class AShooterWeapon* CallFunc_GetWeapon_ReturnValue, class UObject* CallFunc_GetClassDefaultObject_ReturnValue, class AWeap_Torch_Base_C* K2Node_DynamicCast_AsWeap_Torch_Base, bool K2Node_DynamicCast_bSuccess_1, bool CallFunc_CanTorchBeOnBelt_bCanBeOnBelt, bool CallFunc_IsValidClass_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, class FName K2Node_Event_ContextItem, class AShooterPlayerController* K2Node_Event_ForPC, class UPrimalItem* K2Node_Event_DestinationItem, int32 K2Node_Event_AdditionalData, class APawn* CallFunc_K2_GetPawn_ReturnValue, class AShooterCharacter* K2Node_DynamicCast_AsShooter_Character_1, bool K2Node_DynamicCast_bSuccess_2, class UPrimalItemArmor_SaddleGeneric_C* K2Node_DynamicCast_AsPrimal_Item_Armor_Saddle_Generic, bool K2Node_DynamicCast_bSuccess_3, bool CallFunc_IsPreInventoryItem_ReturnValue, bool CallFunc_EqualEqual_NameName_ReturnValue, bool CallFunc_EqualEqual_NameName_ReturnValue_1, bool CallFunc_EqualEqual_NameName_ReturnValue_2, bool CallFunc_EqualEqual_NameName_ReturnValue_3, bool CallFunc_BooleanOR_ReturnValue);
};

}


