#pragma once

// Dumped with Dumper-7!


namespace SDK
{
//---------------------------------------------------------------------------------------------------------------------
// CLASSES
//---------------------------------------------------------------------------------------------------------------------

// 0x2B8 (0xA10 - 0x758)
// WidgetBlueprintGeneratedClass UI_ParentPage.UI_ParentPage_C
class UUI_ParentPage_C : public UPrimalUI
{
public:
	struct FPointerToUberGraphFrame              UberGraphFrame;                                    // 0x758(0x8)(ContainsInstancedReference, AssetRegistrySearchable, AdvancedDisplay, Protected, BlueprintCallable, BlueprintAuthorityOnly, TextExportTransient, NonPIEDuplicateTransient, ExposeOnSpawn, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UButton*                               Button_NextPage;                                   // 0x760(0x8)(Edit, ZeroConstructor)
	class UButton*                               Button_PrevPage;                                   // 0x768(0x8)(Edit, ZeroConstructor)
	class UButton*                               Button_UninstallAll;                               // 0x770(0x8)(Edit, ZeroConstructor)
	class UHorizontalBox*                        HorizontalBox_FilterBy;                            // 0x778(0x8)(Edit, ZeroConstructor)
	class UHorizontalBox*                        HorizontalBox_FilterByTime;                        // 0x780(0x8)(Edit, ZeroConstructor)
	class UImage*                                Image_194;                                         // 0x788(0x8)(Edit, ZeroConstructor)
	class UImage*                                IMG_NextPage;                                      // 0x790(0x8)(Edit, ZeroConstructor)
	class UImage*                                IMG_NoResultsBackground;                           // 0x798(0x8)(Edit, ZeroConstructor)
	class UImage*                                IMG_PrevPage;                                      // 0x7A0(0x8)(Edit, ZeroConstructor)
	class UMultiLineEditableTextBox*             MultiLineEditableTextBox;                          // 0x7A8(0x8)(Edit, ZeroConstructor)
	class UMultiLineEditableTextBox*             MultiLineEditableTextBox_1;                        // 0x7B0(0x8)(Edit, ZeroConstructor)
	class UVerticalBox*                          NO_MOD_PROJECT;                                    // 0x7B8(0x8)(Edit, ZeroConstructor)
	class UOverlay*                              Overlay_CategorySwap;                              // 0x7C0(0x8)(Edit, ZeroConstructor)
	class UProgressBar*                          ProgressBar_Loading;                               // 0x7C8(0x8)(Edit, ZeroConstructor)
	class UVerticalBox*                          SearchNotFound_ver;                                // 0x7D0(0x8)(Edit, ZeroConstructor)
	class USizeBox*                              SizeBox_4;                                         // 0x7D8(0x8)(Edit, ZeroConstructor)
	class UTextBlock*                            Text_ButtonMessage;                                // 0x7E0(0x8)(Edit, ZeroConstructor)
	class UTextBlock*                            TEXT_Filters;                                      // 0x7E8(0x8)(Edit, ZeroConstructor)
	class UTextBlock*                            TEXT_Pages;                                        // 0x7F0(0x8)(Edit, ZeroConstructor)
	class UTextBlock*                            TEXT_SearchModName;                                // 0x7F8(0x8)(Edit, ZeroConstructor)
	class UThrobber*                             Throbber_Loading;                                  // 0x800(0x8)(Edit, ZeroConstructor)
	class UUI_Button_Ark_Back_C*                 UI_Button_Ark_Back;                                // 0x808(0x8)(Edit, ZeroConstructor)
	class UUI_CategoriesSelect_C*                UI_CategoriesSelect;                               // 0x810(0x8)(Edit, ZeroConstructor)
	class UUI_ClassCategorySelect_C*             UI_ClassSelect;                                    // 0x818(0x8)(Edit, ZeroConstructor)
	class UUI_NoModsFound_C*                     UI_NoInstalledModsFound;                           // 0x820(0x8)(Edit, ZeroConstructor)
	class UUI_CustomComboBox_C*                  UI_SortBySelect;                                   // 0x828(0x8)(Edit, ZeroConstructor)
	class UUI_CustomComboBox_C*                  UI_TimeFilters;                                    // 0x830(0x8)(Edit, ZeroConstructor)
	class UUniformGridPanel*                     UniformGridPanel_GameSlots;                        // 0x838(0x8)(Edit, ZeroConstructor)
	class UWidgetSwitcher*                       WidgetSwitcher_Status;                             // 0x840(0x8)(Edit, ZeroConstructor)
	int32                                        Pages;                                             // 0x848(0x4)(None)
	int32                                        PageNum;                                           // 0x84C(0x4)(None)
	TArray<struct FSTRUCT_Categories>            Categories_Subcategories;                          // 0x850(0x10)(Protected, BlueprintAuthorityOnly, TextExportTransient, ExposeOnSpawn, NativeAccessSpecifierPrivate)
	class FString                                SelectedCategory;                                  // 0x860(0x10)(SimpleDisplay, AdvancedDisplay, BlueprintAuthorityOnly, TextExportTransient, ExposeOnSpawn, NativeAccessSpecifierPrivate)
	bool                                         IsSearchFound;                                     // 0x870(0x1)(None)
	enum class ECFCoreModsSearchSortField        SelectedSortByOption;                              // 0x871(0x1)(None)
	uint8                                        Pad_138B[0x6];                                     // Fixing Size After Last Property  [ Dumper-7 ]
	class UUI_StoreMenu_C*                       UI_StoreMenu;                                      // 0x878(0x8)(ZeroConstructor)
	class FString                                CombinedAuthorsNames;                              // 0x880(0x10)(AutoWeak, AdvancedDisplay, Protected, BlueprintCallable, BlueprintAuthorityOnly, TextExportTransient, NonPIEDuplicateTransient, ExposeOnSpawn, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	TArray<struct FModAuthor>                    AuthorsForCheck;                                   // 0x890(0x10)(ContainsInstancedReference, AssetRegistrySearchable, SimpleDisplay, Protected, BlueprintCallable, BlueprintAuthorityOnly, TextExportTransient, NonPIEDuplicateTransient, ExposeOnSpawn, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	TArray<struct FInstallProgressMod>           CurrentClassMods;                                  // 0x8A0(0x10)(ZeroConstructor, ContainsInstancedReference, AssetRegistrySearchable, SimpleDisplay, BlueprintAuthorityOnly, TextExportTransient, ExposeOnSpawn, NativeAccessSpecifierPrivate)
	int32                                        ModsPerPage;                                       // 0x8B0(0x4)(None)
	bool                                         IsPageLoaded;                                      // 0x8B4(0x1)(None)
	uint8                                        Pad_138E[0x3];                                     // Fixing Size After Last Property  [ Dumper-7 ]
	class FText                                  CurrentSearchInput;                                // 0x8B8(0x18)(ContainsInstancedReference, SimpleDisplay, NonPIEDuplicateTransient, ExposeOnSpawn, NativeAccessSpecifierPrivate)
	bool                                         IsCurrentActiveWidget;                             // 0x8D0(0x1)(None)
	bool                                         IsClassCategoriesModAmountLocal;                   // 0x8D1(0x1)(None)
	uint8                                        Pad_1390[0x2];                                     // Fixing Size After Last Property  [ Dumper-7 ]
	int32                                        ModsPerRow;                                        // 0x8D4(0x4)(None)
	class FText                                  PageTitle;                                         // 0x8D8(0x18)(ContainsInstancedReference, AssetRegistrySearchable, NonPIEDuplicateTransient, ExposeOnSpawn, NativeAccessSpecifierPrivate)
	bool                                         IsDownloading;                                     // 0x8F0(0x1)(None)
	uint8                                        Pad_1391[0x7];                                     // Fixing Size After Last Property  [ Dumper-7 ]
	class FString                                GameVersion;                                       // 0x8F8(0x10)(AssetRegistrySearchable, NonPIEDuplicateTransient, ExposeOnSpawn, NativeAccessSpecifierPrivate)
	class FString                                SearchFilter;                                      // 0x908(0x10)(ContainsInstancedReference, AdvancedDisplay, Protected, NonPIEDuplicateTransient, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	int32                                        TotalModsResult_Count;                             // 0x918(0x4)(None)
	enum class ENUM_TimeFilters                  Selected_Default_Option;                           // 0x91C(0x1)(None)
	uint8                                        Pad_1393[0x3];                                     // Fixing Size After Last Property  [ Dumper-7 ]
	TMap<class FString, class UTexture2DDynamic*> Images;                                            // 0x920(0x50)(ZeroConstructor, AssetRegistrySearchable, SimpleDisplay, Protected, BlueprintCallable, BlueprintAuthorityOnly, TextExportTransient, NonPIEDuplicateTransient, ExposeOnSpawn, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	int32                                        MaxImagesCached;                                   // 0x970(0x4)(None)
	uint8                                        Pad_1394[0x4];                                     // Fixing Size After Last Property  [ Dumper-7 ]
	TArray<enum class ECFCoreModsSearchSortField> Array;                                             // 0x978(0x10)(AutoWeak, ContainsInstancedReference, AssetRegistrySearchable, Protected, BlueprintCallable, BlueprintAuthorityOnly, TextExportTransient, NonPIEDuplicateTransient, ExposeOnSpawn, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	TArray<enum class EGameModsEvent>            Evts;                                              // 0x988(0x10)(ContainsInstancedReference, Protected, BlueprintCallable, BlueprintAuthorityOnly, TextExportTransient, NonPIEDuplicateTransient, ExposeOnSpawn, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	TArray<class FString>                        ThumbnailsRequested;                               // 0x998(0x10)(AutoWeak, ContainsInstancedReference, AssetRegistrySearchable, SimpleDisplay, AdvancedDisplay, BlueprintCallable, BlueprintAuthorityOnly, TextExportTransient, NonPIEDuplicateTransient, ExposeOnSpawn, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	int32                                        ImageDownloadingRow;                               // 0x9A8(0x4)(None)
	uint8                                        Pad_1398[0x4];                                     // Fixing Size After Last Property  [ Dumper-7 ]
	TArray<struct FInstallProgressMod>           TrueModInfo;                                       // 0x9B0(0x10)(ZeroConstructor, AutoWeak, ContainsInstancedReference, AssetRegistrySearchable, SimpleDisplay, Protected, NonPIEDuplicateTransient, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	TMap<class FString, enum class ECFCoreModsSearchSortField> SortMap;                                           // 0x9C0(0x50)(None)

	static class UClass* StaticClass();
	static class UUI_ParentPage_C* GetDefaultObj();

	void GetClose_B(class UWidget* Widget);
	void GetVisibility_0(enum class ESlateVisibility ReturnValue, class UCFCoreUISubsystem* CallFunc_GetGameInstanceSubsystem_ReturnValue, bool CallFunc_IsValid_ReturnValue, bool CallFunc_IsAnyModInstalling_ReturnValue, class UUI_ParentPage_C* CallFunc_GetCurrentActivePage_CurrentPage, enum class ENUM_SideTabs CallFunc_GetCurrentActivePage_CurrentActiveTab, bool Temp_bool_Variable, bool K2Node_SwitchEnum_CmpSuccess, enum class ESlateVisibility Temp_byte_Variable, enum class ESlateVisibility Temp_byte_Variable_1, bool CallFunc_IsValid_ReturnValue_1, bool CallFunc_Array_IsValidIndex_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue, bool CallFunc_BooleanOR_ReturnValue, enum class ESlateVisibility K2Node_Select_Default);
	void ReturnModsOfCurrentPage(const TArray<struct FInstallProgressMod>& Mod_List, const TArray<struct FInstallProgressMod>& TrueModInfo, const TArray<struct FInstallProgressMod>& FinalOutputArray, const TArray<struct FInstallProgressMod>& TempArray, int32 Temp_int_Variable, int32 CallFunc_Add_IntInt_ReturnValue, bool Temp_bool_Variable, bool CallFunc_Not_PreBool_ReturnValue, bool CallFunc_IsValid_ReturnValue, int32 CallFunc_Array_Add_ReturnValue, class UUI_ParentPage_C* CallFunc_GetCurrentActivePage_CurrentPage, enum class ENUM_SideTabs CallFunc_GetCurrentActivePage_CurrentActiveTab, bool K2Node_SwitchEnum_CmpSuccess, bool K2Node_SwitchEnum_CmpSuccess_1, bool CallFunc_Array_IsValidIndex_ReturnValue, int32 CallFunc_Int32_SubOne_ReturnValue, int32 CallFunc_Multiply_IntInt_ReturnValue, int32 CallFunc_Multiply_IntInt_ReturnValue_1, int32 CallFunc_Int32_SubOne_ReturnValue_1, bool CallFunc_LessEqual_IntInt_ReturnValue, bool CallFunc_BooleanAND_ReturnValue);
	void MoreImagesLeftToDownload(bool ReturnValue, int32 CallFunc_CalculateModsPerRow_Mods, int32 CallFunc_Multiply_IntInt_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Greater_IntInt_ReturnValue);
	void GetModIndexesForCurrentRow(int32 First, int32 Last, int32 CallFunc_CalculateModsPerRow_Mods, int32 CallFunc_Subtract_IntInt_ReturnValue, int32 CallFunc_Multiply_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue_1);
	void DownloadNextBatchOfMods(int32 Temp_int_Variable, int32 CallFunc_Add_IntInt_ReturnValue, bool CallFunc_EqualEqual_IntInt_ReturnValue);
	void DownloadBatchOfMods(int32 Temp_int_Variable, int32 CallFunc_Add_IntInt_ReturnValue, const struct FInstallProgressMod& CallFunc_Array_Get_Item, bool CallFunc_Array_IsValidIndex_ReturnValue, class UUI_GameSlot_C* K2Node_DynamicCast_AsUI_Game_Slot, bool K2Node_DynamicCast_bSuccess, int32 CallFunc_GetModIndexesForCurrentRow_First, int32 CallFunc_GetModIndexesForCurrentRow_Last, bool CallFunc_IsValid_ReturnValue, bool CallFunc_LessEqual_IntInt_ReturnValue, const class FString& CallFunc_Array_Get_Item_1);
	void CheckIfImagesAreReady(bool CallFunc_MoreImagesLeftToDownload_ReturnValue, int32 Temp_int_Variable, int32 CallFunc_Add_IntInt_ReturnValue, bool Temp_bool_Variable, bool CallFunc_Not_PreBool_ReturnValue, const struct FInstallProgressMod& CallFunc_Array_Get_Item, bool CallFunc_Array_IsValidIndex_ReturnValue, class UUI_GameSlot_C* K2Node_DynamicCast_AsUI_Game_Slot, bool K2Node_DynamicCast_bSuccess, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Greater_IntInt_ReturnValue, bool CallFunc_IsValid_ReturnValue, int32 CallFunc_GetModIndexesForCurrentRow_First, int32 CallFunc_GetModIndexesForCurrentRow_Last, bool CallFunc_LessEqual_IntInt_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, const class FString& CallFunc_Array_Get_Item_1, bool CallFunc_EqualEqual_StrStr_ReturnValue);
	void DownloadImagesInAllMods(bool CallFunc_InitiliazeImageDownloads_ReadyToStart);
	void CreateEmptySlot(int32 AtIndex, int32 CallFunc_CalculateModsPerRow_Mods, bool CallFunc_IsValid_ReturnValue, int32 CallFunc_Percent_IntInt_ReturnValue, int32 CallFunc_Divide_IntInt_ReturnValue, class UUI_EmptySlot_C* CallFunc_Create_ReturnValue, class UUniformGridSlot* CallFunc_AddChildToUniformGrid_ReturnValue);
	void SwitchControllerAction(const struct FKey& Key, enum class EViewState State, bool CallFunc_EqualEqual_ByteByte_ReturnValue, bool CallFunc_EqualEqual_KeyKey_ReturnValue);
	void Nav_Down_from_DropdownTime(enum class EUINavigation Navigation, class UWidget* ReturnValue, class UWidget* CallFunc_Nav_to_Options_ReturnValue, class UWidget* CallFunc_GetChildAt_ReturnValue, class UUI_GameSlot_C* K2Node_DynamicCast_AsUI_Game_Slot, bool K2Node_DynamicCast_bSuccess, bool CallFunc_IsVisible_ReturnValue);
	void Nav_Down_from_DropdownSort(enum class EUINavigation Navigation, class UWidget* ReturnValue, class UWidget* CallFunc_Nav_to_Options_ReturnValue, class UWidget* CallFunc_GetChildAt_ReturnValue, class UUI_GameSlot_C* K2Node_DynamicCast_AsUI_Game_Slot, bool K2Node_DynamicCast_bSuccess, bool CallFunc_IsVisible_ReturnValue);
	void Nav_Down_from_DropdownCategory(enum class EUINavigation Navigation, class UWidget* ReturnValue, class UWidget* CallFunc_Nav_to_Options_ReturnValue, class UWidget* CallFunc_GetChildAt_ReturnValue, class UUI_GameSlot_C* K2Node_DynamicCast_AsUI_Game_Slot, bool K2Node_DynamicCast_bSuccess, bool CallFunc_IsVisible_ReturnValue);
	void Nav_for_Up_Move_from_List(enum class EUINavigation Navigation, class UWidget* ReturnValue);
	void SetNavigationRuleForList(int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, bool K2Node_SwitchInteger_CmpSuccess, int32 CallFunc_Add_IntInt_ReturnValue, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate, const TArray<class UWidget*>& CallFunc_GetAllChildren_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, class UWidget* CallFunc_Array_Get_Item, bool CallFunc_Less_IntInt_ReturnValue);
	void SetListFocus(class UWidget* CallFunc_GetChildAt_ReturnValue, class UUI_GameSlot_C* K2Node_DynamicCast_AsUI_Game_Slot, bool K2Node_DynamicCast_bSuccess);
	void UpdatePaginations(const TArray<struct FInstallProgressMod>& TotalList, bool Temp_bool_Variable, int32 CallFunc_Array_Length_ReturnValue, int32 CallFunc_CalculateModsPerPage_Mods, double CallFunc_Conv_IntToDouble_ReturnValue, double CallFunc_Conv_IntToDouble_ReturnValue_1, double CallFunc_FMod_Remainder, int32 CallFunc_FMod_ReturnValue, bool CallFunc_Greater_DoubleDouble_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, int32 K2Node_Select_Default);
	void ClearImageCache(int32 CallFunc_Map_Length_ReturnValue, bool CallFunc_Greater_IntInt_ReturnValue);
	void BindToDropdown(int32 Temp_int_Variable, int32 Temp_int_Variable_1, int32 CallFunc_Add_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_1, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate_1, const TArray<class UUI_CustomComboBox_C*>& K2Node_MakeArray_Array, int32 CallFunc_Array_Length_ReturnValue, class UUI_CustomComboBox_C* CallFunc_Array_Get_Item, bool CallFunc_Less_IntInt_ReturnValue, int32 CallFunc_Array_Length_ReturnValue_1, class UUI_CustomComboBox_C* CallFunc_Array_Get_Item_1, bool CallFunc_Less_IntInt_ReturnValue_1);
	void CloseNotAllDropdown(class UUI_CustomComboBox_C* Dropdown, const TArray<class UUI_CustomComboBox_C*>& Dropdowns, int32 Temp_int_Variable, int32 CallFunc_Add_IntInt_ReturnValue, class UUI_CustomComboBox_C* CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Array_RemoveItem_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, class UBindButtonSystem* CallFunc_GetEngineSubsystem_ReturnValue, const TArray<class UUI_CustomComboBox_C*>& K2Node_MakeArray_Array);
	void CloseAllDropDown(int32 Temp_int_Variable, class UBindButtonSystem* CallFunc_GetEngineSubsystem_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, const TArray<class UUI_CustomComboBox_C*>& K2Node_MakeArray_Array, int32 CallFunc_Array_Length_ReturnValue, class UUI_CustomComboBox_C* CallFunc_Array_Get_Item, bool CallFunc_Less_IntInt_ReturnValue);
	void SetEnableStageForGameSlot(bool EnableStage, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, const TArray<class UWidget*>& CallFunc_GetAllChildren_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, class UWidget* CallFunc_Array_Get_Item, bool CallFunc_Less_IntInt_ReturnValue, class UUI_GameSlot_C* K2Node_DynamicCast_AsUI_Game_Slot, bool K2Node_DynamicCast_bSuccess);
	void BindToGameSlot(int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate, const TArray<class UWidget*>& CallFunc_GetAllChildren_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, class UWidget* CallFunc_Array_Get_Item, bool CallFunc_Less_IntInt_ReturnValue, class UUI_GameSlot_C* K2Node_DynamicCast_AsUI_Game_Slot, bool K2Node_DynamicCast_bSuccess);
	void ClearAllModsInPage(int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, int32 Temp_int_Array_Index_Variable, bool CallFunc_IsValid_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, const struct FInstallProgressMod& CallFunc_Array_Get_Item, bool CallFunc_Less_IntInt_ReturnValue, bool CallFunc_IsValid_ReturnValue_1);
	void UpdateNotificationInSwitcher(bool CallFunc_IsValid_ReturnValue, bool CallFunc_IsValid_ReturnValue_1, class UUI_ParentPage_C* CallFunc_GetCurrentActivePage_CurrentPage, enum class ENUM_SideTabs CallFunc_GetCurrentActivePage_CurrentActiveTab, bool K2Node_SwitchEnum_CmpSuccess, bool CallFunc_IsEmpty_ReturnValue, bool CallFunc_IsValid_ReturnValue_2, int32 CallFunc_SelectInt_ReturnValue, bool CallFunc_IsValid_ReturnValue_3, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_EqualEqual_IntInt_ReturnValue, bool CallFunc_IsValid_ReturnValue_4);
	void InitWidgetStoreMenuRefs();
	void UpdateAllThemeSettings(bool CallFunc_IsValid_ReturnValue, const struct FSlateColor& K2Node_MakeStruct_SlateColor);
	void IsUrlValid(const class FString& URL, bool ReturnValue, bool CallFunc_EqualEqual_StrStr_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue);
	void UpdatePagesPagination(bool CallFunc_IsValid_ReturnValue, int64 CallFunc_Conv_IntToInt64_ReturnValue, const struct FFormatArgumentData& K2Node_MakeStruct_FormatArgumentData, int64 CallFunc_Conv_IntToInt64_ReturnValue_1, const struct FFormatArgumentData& K2Node_MakeStruct_FormatArgumentData_1, const TArray<struct FFormatArgumentData>& K2Node_MakeArray_Array, class FText CallFunc_Format_ReturnValue);
	void FilterModInfo(const struct FCFCoreSearchModsFilter& ReturnValue, int32 CallFunc_Conv_Int64ToInt_ReturnValue, int32 CallFunc_Conv_Int64ToInt_ReturnValue_1, const struct FCFCoreSearchModsFilter& CallFunc_MakeSearchModsFilter_ReturnValue);
	void GetCurrentTab(enum class ENUM_SideTabs CurrentActiveTab);
	void UpdateSearchText(class FText CallFunc_Conv_IntToText_ReturnValue, bool CallFunc_IsValid_ReturnValue, bool CallFunc_IsValid_ReturnValue_1, class FText CallFunc_Conv_StringToText_ReturnValue, const class FString& CallFunc_Concat_StrStr_ReturnValue, const class FString& CallFunc_Concat_StrStr_ReturnValue_1, class FText CallFunc_Conv_StringToText_ReturnValue_1);
	void LoadSavedUpImagesAsync(int32 Temp_int_Variable, int32 CallFunc_Add_IntInt_ReturnValue, const struct FInstallProgressMod& CallFunc_Array_Get_Item, bool CallFunc_Array_IsValidIndex_ReturnValue, class UUI_GameSlot_C* K2Node_DynamicCast_AsUI_Game_Slot, bool K2Node_DynamicCast_bSuccess, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Greater_IntInt_ReturnValue, bool CallFunc_IsValid_ReturnValue, int32 CallFunc_GetModIndexesForCurrentRow_First, int32 CallFunc_GetModIndexesForCurrentRow_Last, bool CallFunc_LessEqual_IntInt_ReturnValue);
	void InitiliazeImageDownloads(bool ReadyToStart, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, const struct FInstallProgressMod& CallFunc_Array_Get_Item, bool CallFunc_Array_IsValidIndex_ReturnValue, class UUI_GameSlot_C* K2Node_DynamicCast_AsUI_Game_Slot, bool K2Node_DynamicCast_bSuccess, bool CallFunc_IsValid_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, int32 CallFunc_Array_Length_ReturnValue_1, bool CallFunc_Less_IntInt_ReturnValue, bool CallFunc_Greater_IntInt_ReturnValue, int32 CallFunc_Array_Add_ReturnValue);
	void CalculateModsPerRow(int32 Mods, class UGameUserSettings* CallFunc_GetGameUserSettings_ReturnValue, const struct FIntPoint& CallFunc_GetScreenResolution_ReturnValue, double CallFunc_Conv_IntToDouble_ReturnValue, double CallFunc_Conv_IntToDouble_ReturnValue_1, double CallFunc_Divide_DoubleDouble_ReturnValue, bool CallFunc_NearlyEqual_FloatFloat_ReturnValue, bool CallFunc_Greater_DoubleDouble_ReturnValue);
	void CalculateModsPerPage(int32 Mods, class UGameUserSettings* CallFunc_GetGameUserSettings_ReturnValue, const struct FIntPoint& CallFunc_GetScreenResolution_ReturnValue, double CallFunc_Conv_IntToDouble_ReturnValue, double CallFunc_Conv_IntToDouble_ReturnValue_1, double CallFunc_Divide_DoubleDouble_ReturnValue, bool CallFunc_NearlyEqual_FloatFloat_ReturnValue, bool CallFunc_Greater_DoubleDouble_ReturnValue);
	void PrevPage(int32 Temp_int_Variable, bool CallFunc_IsValid_ReturnValue, bool CallFunc_Greater_IntInt_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue);
	void NextPage(int32 Temp_int_Variable, bool CallFunc_IsValid_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue);
	void GetCurrentSearchInput(class FText CurrentSearchInput);
	void OnPageActiveted(class FText Search_Input);
	void SetCurrentClassMods(bool CallFunc_IsValid_ReturnValue, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, const struct FInstallProgressMod& CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, int64 CallFunc_Conv_IntToInt64_ReturnValue, bool CallFunc_EqualEqual_Int64Int64_ReturnValue, int32 CallFunc_Array_Add_ReturnValue);
	void ResetPageNum();
	void SetStypleOfPageArrowsButtons(const struct FSlateColor& K2Node_MakeStruct_SlateColor, const struct FSlateColor& K2Node_MakeStruct_SlateColor_1, const struct FSlateColor& K2Node_MakeStruct_SlateColor_2, const struct FSlateColor& K2Node_MakeStruct_SlateColor_3, bool CallFunc_EqualEqual_IntInt_ReturnValue, bool CallFunc_EqualEqual_IntInt_ReturnValue_1, bool CallFunc_BooleanOR_ReturnValue, bool CallFunc_EqualEqual_IntInt_ReturnValue_2);
	void UpdateCategoriesSelect(bool CallFunc_IsModsListEmpty_IsEmpty);
	void CreateModSlot(int32 AtIndex, class UUI_GameSlot_C* CallFunc_Create_ReturnValue, const struct FInstallProgressMod& K2Node_MakeStruct_InstallProgressMod, int32 CallFunc_CalculateModsPerRow_Mods, int32 CallFunc_Divide_IntInt_ReturnValue, int32 CallFunc_Percent_IntInt_ReturnValue, class UUniformGridSlot* CallFunc_AddChildToUniformGrid_ReturnValue);
	void IsSearchInputValid(bool Return_Value, bool CallFunc_TextIsEmpty_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue);
	void OnPageLoaded();
	void SearchForAuthorsName(class FText Input, const TArray<struct FModAuthor>& Authors, bool AuthorFound, int32 CallFunc_Array_Length_ReturnValue, const class FString& CallFunc_Conv_TextToString_ReturnValue, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, const struct FModAuthor& CallFunc_Array_Get_Item, bool CallFunc_Less_IntInt_ReturnValue, int32 CallFunc_FindSubstring_ReturnValue, bool CallFunc_NotEqual_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue);
	void UpdateClasses();
	void SetupTimeFilter(enum class ENUM_TimeFilters SelectedDefaultOption, const class FString& CallFunc_GetEnumeratorUserFriendlyName_ReturnValue, int32 Temp_int_Variable, int32 Temp_int_Variable_1, uint8 CallFunc_Conv_IntToByte_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, uint8 CallFunc_GetValidValue_ReturnValue, uint8 CallFunc_Conv_IntToByte_ReturnValue_1, const class FString& CallFunc_GetEnumeratorUserFriendlyName_ReturnValue_1, uint8 CallFunc_GetEnumeratorValueFromIndex_ReturnValue, const struct FSTRUCT_CustomComboBoxOption& K2Node_MakeStruct_STRUCT_CustomComboBoxOption, int32 CallFunc_Conv_ByteToInt_ReturnValue, int32 CallFunc_MakeLiteralInt_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue);
	void SetupSortByOptions(enum class ECFCoreModsSearchSortField SelectedDefaultOption, const class FString& Temp_string_Variable, const class FString& Temp_string_Variable_1, const class FString& Temp_string_Variable_2, const class FString& Temp_string_Variable_3, const class FString& Temp_string_Variable_4, const class FString& Temp_string_Variable_5, const class FString& Temp_string_Variable_6, const class FString& Temp_string_Variable_7, const class FString& Temp_string_Variable_8, const class FString& Temp_string_Variable_9, const class FString& Temp_string_Variable_10, const class FString& Temp_string_Variable_11, enum class ECFCoreModsSearchSortField Temp_byte_Variable, const class FString& Temp_string_Variable_12, const class FString& Temp_string_Variable_13, const class FString& Temp_string_Variable_14, const class FString& Temp_string_Variable_15, const class FString& Temp_string_Variable_16, const class FString& Temp_string_Variable_17, const class FString& Temp_string_Variable_18, const class FString& Temp_string_Variable_19, const class FString& Temp_string_Variable_20, const class FString& Temp_string_Variable_21, const class FString& Temp_string_Variable_22, const class FString& Temp_string_Variable_23, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, enum class ECFCoreModsSearchSortField Temp_byte_Variable_1, const TArray<enum class ECFCoreModsSearchSortField>& K2Node_MakeArray_Array, enum class ECFCoreModsSearchSortField CallFunc_Array_Get_Item, enum class ECFCoreModsSearchSortField CallFunc_Array_Get_Item_1, const class FString& K2Node_Select_Default, const class FString& K2Node_Select_Default_1, const struct FSTRUCT_CustomComboBoxOption& K2Node_MakeStruct_STRUCT_CustomComboBoxOption, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue);
	void SelectClass(bool CallFunc_IsValid_ReturnValue, bool CallFunc_IsValid_ReturnValue_1);
	void OnMouseButtonDown(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent, const struct FEventReply& ReturnValue, bool CallFunc_PointerEvent_IsMouseButtonDown_ReturnValue, bool CallFunc_IsValid_ReturnValue, const struct FEventReply& CallFunc_Handled_ReturnValue);
	void BuildPage(bool Temp_bool_Variable, int32 Temp_int_Variable, int32 CallFunc_Subtract_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue, int32 CallFunc_CalculateModsPerPage_Mods, int32 CallFunc_Array_LastIndex_ReturnValue, bool CallFunc_LessEqual_IntInt_ReturnValue, bool CallFunc_LessEqual_IntInt_ReturnValue_1, bool CallFunc_BooleanAND_ReturnValue);
	void CheckWhichTextAppearsFirst(class FText NameOne, class FText NameTwo, bool Name_One_Appears_First, int32 _numOfLettersForCheck, bool Temp_bool_Variable, const class FString& CallFunc_Conv_TextToString_ReturnValue, const class FString& CallFunc_ToUpper_ReturnValue, const TArray<class FString>& CallFunc_GetCharacterArrayFromString_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue, const class FString& CallFunc_Conv_TextToString_ReturnValue_1, const class FString& CallFunc_ToUpper_ReturnValue_1, const TArray<class FString>& CallFunc_GetCharacterArrayFromString_ReturnValue_1, int32 CallFunc_Array_Length_ReturnValue_1, bool CallFunc_Greater_IntInt_ReturnValue, int32 Temp_int_Variable, int32 CallFunc_GetCharacterAsNumber_ReturnValue, bool CallFunc_LessEqual_IntInt_ReturnValue, int32 CallFunc_GetCharacterAsNumber_ReturnValue_1, bool CallFunc_BooleanAND_ReturnValue, bool CallFunc_Greater_IntInt_ReturnValue_1, bool CallFunc_NotEqual_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue);
	void IsModsListEmpty(bool IsEmpty, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_EqualEqual_IntInt_ReturnValue);
	void BndEvt__ParentPageWidget_SortBySelect_K2Node_ComponentBoundEvent_4_OnOptionSelected__DelegateSignature(const class FString& Option);
	void BndEvt__ParentPageWidget_CategoriesSelect2_K2Node_ComponentBoundEvent_5_OnOptionSelected__DelegateSignature(const class FString& Option);
	void Event_On_Input_Device_Changed(enum class ENUM_InputDevices Device);
	void Event_Update_Filter_By_Options(int64 Current_Class_Category_ID);
	void BndEvt__UI_ParentPage_Button_NextPage_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__UI_ParentPage_Button_PrevPage_K2Node_ComponentBoundEvent_12_OnButtonClickedEvent__DelegateSignature();
	void Event_On_Class_Selected();
	void Event_Search_Mods();
	void ConstructParentPage();
	void FillTheModList();
	void GetMods();
	void UpdateSearch(class FText SearchInput);
	void Construct();
	void BndEvt__UI_ParentPage_UI_Button_Ark_Back_K2Node_ComponentBoundEvent_1_OnClick__DelegateSignature();
	void OnSearch(class FText Search_Input);
	void ButtonCall(const struct FKey& Key, enum class EViewState State);
	void BindControllerAction();
	void NextPageButton();
	void PrevPageButton();
	void PreConstruct(bool IsDesignTime);
	void ExecuteUbergraph_UI_ParentPage(int32 EntryPoint, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate, class UBindButtonSystem* CallFunc_GetEngineSubsystem_ReturnValue, bool CallFunc_IsValid_ReturnValue, const class FString& K2Node_ComponentBoundEvent_Option_1, const class FString& K2Node_ComponentBoundEvent_Option, enum class ENUM_InputDevices K2Node_CustomEvent_Device, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate_1, int64 K2Node_CustomEvent_Current_Class_Category_ID, bool CallFunc_IsValid_ReturnValue_1, class FText K2Node_Event_SearchInput, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate_2, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate_3, class FText K2Node_Event_Search_Input, const struct FKey& K2Node_CustomEvent_Key, enum class EViewState K2Node_CustomEvent_State, bool CallFunc_IsValid_ReturnValue_2, bool K2Node_Event_IsDesignTime, enum class ECFCoreModsSearchSortField CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue, bool CallFunc_EqualEqual_ByteByte_ReturnValue);
};

}


